# permissions for end users to edit ocirepositories.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ocirepository-editor-role
rules:
- apiGroups:
  - cd.qdrant.io
  resources:
  - ocirepositories
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cd.qdrant.io
  resources:
  - ocirepositories/status
  verbs:
  - get
