# permissions for end users to view ocirepositories.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ocirepository-viewer-role
rules:
- apiGroups:
  - cd.qdrant.io
  resources:
  - ocirepositories
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cd.qdrant.io
  resources:
  - ocirepositories/status
  verbs:
  - get
