---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cd.qdrant.io
  resources:
  - buckets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cd.qdrant.io
  resources:
  - buckets/finalizers
  verbs:
  - create
  - delete
  - get
  - patch
  - update
- apiGroups:
  - cd.qdrant.io
  resources:
  - buckets/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - cd.qdrant.io
  resources:
  - gitrepositories
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cd.qdrant.io
  resources:
  - gitrepositories/finalizers
  verbs:
  - create
  - delete
  - get
  - patch
  - update
- apiGroups:
  - cd.qdrant.io
  resources:
  - gitrepositories/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - cd.qdrant.io
  resources:
  - helmcharts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cd.qdrant.io
  resources:
  - helmcharts/finalizers
  verbs:
  - create
  - delete
  - get
  - patch
  - update
- apiGroups:
  - cd.qdrant.io
  resources:
  - helmcharts/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - cd.qdrant.io
  resources:
  - helmrepositories
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cd.qdrant.io
  resources:
  - helmrepositories/finalizers
  verbs:
  - create
  - delete
  - get
  - patch
  - update
- apiGroups:
  - cd.qdrant.io
  resources:
  - helmrepositories/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - cd.qdrant.io
  resources:
  - ocirepositories
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cd.qdrant.io
  resources:
  - ocirepositories/finalizers
  verbs:
  - create
  - delete
  - get
  - patch
  - update
- apiGroups:
  - cd.qdrant.io
  resources:
  - ocirepositories/status
  verbs:
  - get
  - patch
  - update
